### ISSUE TITLE
Crash when breaking random item box with no sidekick or stocks in Encore Mode

### ISSUE THREAD

**Issue by MegAmi24** [RSDKModding/Sonic-Mania-Decompilation#283]
Steps to reproduce:
1. Boot up game, start a new game in Encore Mode
2. When you get to GHZ, die as one of the characters, don't get any new stocks before or afterwards
3. Break a random item box

https://github.com/user-attachments/assets/913ff3c8-417e-4afc-836f-df4b3d5c61f9

**Comment by MegAmi24** [comment]
Looked in VS Debugger, there are two things causing this:

**Comment by Mefiresu** [comment]
Fixed by https://github.com/RSDKModding/RSDKv5-Decompilation/commit/a80e2ba8600b210f79208bf5d3bd357627f5d63d

**Explanation**:
- To destroy an entity, the game usually calls ResetEntity with TYPE_BLANK as classID, which is DefaultObject.
- The engine takes the entity pointer, retrieves the size of the given classID (TYPE_BLANK here), and retrieves the entityClassSize for this classID. It then uses this size to run a `memset(0)` on the entity.
- The bug was triggered because DefaultObject was registered with a size of `sizeof(ObjectDefaultObject) == 0x58`, which is valid in pre-plus but was changed starting with Plus to account for the largest possible size for an entity `sizeof(EntityBase) == 0x458`.

In Encore mode, when you die, the game will swap your current character with the sidekick, and then reset the dead character's entity.
The random item box tries to check for the `characterID` of the sidekick, but since it has been reset, we actually expect 0.
The part of memory that was storing the `characterID` never got erased because of the smaller DefaultObject size, so it returned the old value, causing a softlock.
